CC := gcc
LDLIBS := -Wall -Wextra -Werror -pthread

SRC_DOWNLOADER = src/parallel_downloader.c
OBJS_PARRALEL_DOWNLOADER = $(SRC_DOWNLOADER:.c=.o)
TARGET_PARRALEL_DOWNLOADER = parallel_downloader

.PHONY: TARGET_PARRALEL_DOWNLOADER
$(TARGET_PARRALEL_DOWNLOADER): $(OBJS_PARRALEL_DOWNLOADER)

.PHONY: clean
clean:
	$(RM) $(TARGET_PARRALEL_DOWNLOADER) $(OBJS_PARRALEL_DOWNLOADER)